export const GET_TYPES = 'GET_TYPES';
export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKE_BY_ID = 'GET_POKE_BY_ID';
export const GET_POKE_BY_NAME = 'GET_POKE_BY_NAME';
export const GET_POKES_FILTERED_TYPES = 'GET_POKES_FILTERED_TYPES';
export const GET_POKES_FILTERED_ORIGIN = 'GET_POKES_FILTERED_ORIGIN';
export const GET_POKES_ORDER_ATTACK = 'GET_POKES_ORDER_ATTACK';
export const GET_POKES_ORDER_ALPHABETIC = 'GET_POKES_ORDER_ALPHABETIC';

export const POST_POKEMON = 'POST_POKEMON';
export const FETCHED_ERRORS = 'FETCHED_ERRORS'